// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/bin.ts";
import * as $$$1 from "./loaders/product/productDetailsPage.ts";
import * as $$$2 from "./loaders/product/productList.ts";
import { AppManifest } from "$live/types.ts";

const manifest = {
  "loaders": {
    "salesforce-integration/loaders/bin.ts": $$$0,
    "salesforce-integration/loaders/product/productDetailsPage.ts": $$$1,
    "salesforce-integration/loaders/product/productList.ts": $$$2,
  },
};

export type Manifest = typeof manifest;

export const name = "salesforce-integration";

export default manifest satisfies AppManifest;
